### ISSUE TITLE
OSX version not loading

### ISSUE THREAD

**Issue by muranava** [BLKSerene/Wordless#1]
hi
thx for this tool, i tried using the OSX version but program does not want to start; 
sorry i can't get any diagnostic info from Console for some reason; 
my system is 10.11.6
thx

**Comment by BLKSerene** [comment]
Hi, did you download Wordless from the link in my homepage?
If this does not work for you, please try upgrading your macOS to the lastest version.

**Comment by muranava** [comment]
hi
yes the version is from the download page;
unfortunately i am on the max recommended update for my hardware

**Comment by BLKSerene** [comment]
Could you please right click on `Wordless.app`, select `Show Package Contents`, navigate to `Contents/MacOS,` double-click `Wordless`, and paste the error mesaage here?

**Comment by muranava** [comment]
-----
Traceback (most recent call last):
  File "src/wordless_main.py", line 24, in <module>
ImportError: dlopen(/Users/muranava/Downloads/Wordless.app/Contents/MacOS/PyQt5/QtCore.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Users/muranava/Downloads/Wordless.app/Contents/MacOS/PyQt5/../QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/muranava/Downloads/Wordless.app/Contents/MacOS/PyQt5/../QtCore
[784] Failed to execute script wordless_main
-----

**Comment by BLKSerene** [comment]
Well, it seems to be the problem about macOS's backward compatibility...
Wordless is tested on the latest 10.14. Since I'm on Windows, I'll need some time to test the older versions.
The tool is intended to be used out of the box, without the need for users to install Python or any dependency themselves, so I'll manage this. Sorry for the incovenience, I'll come back to you when I have progress on that.

**Comment by muranava** [comment]
ok thanks!

**Comment by BLKSerene** [comment]
@muranava Sorry for the late reply. I've tried packaging Wordless on older macOS versions, but had no luck with it.

I've checked that the latest version of Qt (5.12) [supports only macOS 10.12-10.14](https://doc.qt.io/qt-5/supported-platforms.html#macos), it may work on macOS 10.11, but since I'm on Windows and it is not officially supported, I'm reluctant to support (and test) it. So you might need a Mac that runs the latest macOS.

But if you do want to try running Wordless on older macOS versions, you could install all the dependencies (there're quite a lot)  and run from source:

1. You need 64-bit Python 3.7 (3.6 should also work, I suppose).

2. Install all denpendencies:
`pip3 install beautifulsoup4 cchardet chardet jieba langdetect langid lxml matplotlib nagisa nltk numpy openpyxl pybo git+https://github.com/kmike/pymorphy2.git pymorphy2-dicts-ru pymorphy2-dicts-uk pyqt5 pythainlp python-docx requests sacremoses scipy spacy-nightly underthesea wordcloud xlrd`

3. Download models for spaCy:
```
python3 -m spacy download de
python3 -m spacy download en
python3 -m spacy download el
python3 -m spacy download es
python3 -m spacy download fr
python3 -m spacy download nl
python3 -m spacy download it
python3 -m spacy download pt
```

4. Download data for NLTK (run the following in IDLE):
```
>>> import nltk
>>> nltk.download('stopwords')
>>> nltk.download('wordnet')
>>> nltk.download('averaged_perceptron_tagger')
>>> nltk.download('averaged_perceptron_tagger_ru')
>>> nltk.download('perluniprops') 
>>> nltk.download('punkt') 
```

5. Run wordless_main.py

**Comment by muranava** [comment]
hi thanks
tried your instructon but getting this error when trying to run wordless_main.py:

-----
Traceback (most recent call last):
  File "wordless_main.py", line 24, in <module>
    from PyQt5.QtCore import *
ImportError: dlopen(/usr/local/lib/python3.7/site-packages/PyQt5/QtCore.so, 2): Symbol not found: __os_activity_create
  Referenced from: /usr/local/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore
------

**Comment by BLKSerene** [comment]
@muranava Could you please try:
`pip3 uninstall pyqt5` # Uninstall the latest version
`pip3 install pyqt5==5.11.3` # PyQt 5.11 supports Qt 5.11 which should support OS X 10.11

But please note that there's a [bug](https://bugreports.qt.io/browse/QTBUG-70633?filter=-2) in this older version of Qt, which would affect some features in Wordless, and that's the reason why I'm reluctant to downgrade.

If you're going to use it on older versions of masOS, you may need to keep using this older version of PyQt, and should not upgrade it.

**Comment by muranava** [comment]
ok great that worked thanks for your support!

**Comment by BLKSerene** [comment]
Thanks for your feed back. To add a note: v1.1.0 is out, and now you can uninstall the alpha version of spaCy and use the latest release of spaCy (and the latest models).

```
pip3 uninstall spacy-nightly
pip3 install spacy

python3 -m spacy download de
python3 -m spacy download en
python3 -m spacy download el
python3 -m spacy download es
python3 -m spacy download fr
python3 -m spacy download nl
python3 -m spacy download it
python3 -m spacy download pt
```

**Comment by BLKSerene** [comment]
Wordless V1.4.0 now supports OS X 10.11

**Comment by BLKSerene** [comment]
@muranava Hi, I'm considering bumping the minimum requirement for macOS operating system. Do you still need the support for OS X 10.11?

**Comment by lin17-1-mGb** [comment]
> @muranava Hi, I'm considering bumping the minimum requirement for macOS operating system. Do you still need the support for OS X 10.11?

hi there, no i don't need support for macos 10.11, thanks

**Comment by muranava** [comment]
hi sorry that was me (alt account) on previous comment - i.e. i don't need support on macos 10.11
thanks
