### ISSUE TITLE
Dependency Parser: `sentence_display` is escaped to HTML

### ISSUE THREAD

**Issue by tanloong** [BLKSerene/Wordless#28]
**Describe the bug**
Some chars like `'` are displayed as HTML in the Sentence column.

**To Reproduce**
1. `echo -e "What's that? The sign & means \"and\"." > sample.txt`
2. Go to the `Dependency Parser` tab
3. Open `sample.txt` and click `Generate table`

**Expected behavior**
Sentences are shown as they actually are.

**Screenshots**
![2023-08-29_11-52](https://github.com/BLKSerene/Wordless/assets/71320000/01cf118d-4b7f-43af-89e5-7f2bce1de750)

**Environment information**
 - Operating System: Arch Linux
 - Wordless Version: 3.3.0

**Additional context**
I dug a bit and found that with [this line](https://github.com/BLKSerene/Wordless/blob/main/wordless/wl_dependency_parser.py#L536) commented, the problem disappears.

![2023-08-29_11-51](https://github.com/BLKSerene/Wordless/assets/71320000/d5a8bb83-683d-45a7-b65e-6d9049672174)

(The `Concordancer` and `Concordancer Parallel` tabs are missing in the screenshots because I disabled them after failing to install some of their dependencies. But the screenshots do belong to Wordless version 3.3.0, though run from source code instead of the compiled release.)

**Comment by BLKSerene** [comment]
Thanks for reporting the issue.
Text in the columns `Left`, `Node`, and `Right` of _Concordancer_ and `Parallel Unit` of _Parallel Concordancer_ needs to be escaped as HTML entities since they are to be inserted in HTML and rendered as rich text (different highlighting color for different words). Otherwise, special characters in raw text would be treated as part of HTML syntax.

But in _Dependency Parser_, no need to escape the text since they are rendered as raw text.

I'll fix it in the next release (3.4.0).

**Comment by BLKSerene** [comment]
Fixed in [3.4.0](https://github.com/BLKSerene/Wordless/releases/tag/3.4.0).
